### PR TITLE
feat: NS7 support

### PR DESCRIPTION
**Pull request by bradmartin**

### CODE REVIEW

**Comment by bradmartin** [comment]
@EddyVerbruggen just an extra nudge on the notifications in case you miss the PR one 😉

**Comment by bradmartin** [comment]
Poke 😉

**Comment by EddyVerbruggen** [comment]
TY Brad! I'll be probably testing and releasing this tomorrow.

**Comment by bradmartin** [comment]
No worries or rush :) thanks as always for all you do ❤️

**Pull request merged**
